/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FieldItem: typeof import('./src/components/FieldItem.vue')['default']
    FieldList: typeof import('./src/components/FieldList.vue')['default']
    FixedFieldsSettings: typeof import('./src/components/FixedFieldsSettings.vue')['default']
    PanelSettings: typeof import('./src/components/PanelSettings.vue')['default']
    PromptEditor: typeof import('./src/components/PromptEditor.vue')['default']
    StatusDisplay: typeof import('./src/components/StatusDisplay.vue')['default']
  }
}
